### ISSUE TITLE
Sorting of team members not working as expected

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#747] opened 2020-11-12 08:21 UTC
**Bug Description**
In `/src/data/teams.json` file all members got **"createdDate": "2020-07-08T02:14:59.307535Z"** and few got **"createdDate": "2020-05-09T02:14:59.307535Z"**. People who got the 2nd one had got their position misplaced and not sorted according to their **contributorId**.

**Steps to Reproduce**
Go to https://thenewboston.com/teams

**Expected behavior**
All members sorted on the basis of **contributorId**

**Actual behavior**
Few members got their position misplaced

**Screenshots/Recordings**
Member with  **contributorId** **5, 18 and 23** got their position misplaced.

![id](https://user-images.githubusercontent.com/22790904/98913102-f4a0e900-24ec-11eb-8b0f-6415b80f99f9.JPG)
![id-2](https://user-images.githubusercontent.com/22790904/98913125-f8cd0680-24ec-11eb-9558-0eb1d7af0e3c.JPG)

**Additional context**
This happened to those members who are in Back-End Developers. Few of them got the 2nd **createdDate**. The possible quick solution is to change their `createdDate` to `2020-07-08T02:14:59.307535Z` because all other members also got the same `createdDate` irrespective of when they joined the team. Or we need to correct the sorting.

**Account Number**
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by asaadat99** [comment] 2020-11-12 23:32
Hello, I am interested in working on this, can you assign it to me?

**Comment by Hristijan95** [comment] 2020-11-12 23:55
@asaadat99 , as you can se above, there's already a PR to fix this from @manishram . However, at the moment the design team is doing a redesign on the Teams/All page, so we'll decide what to do with this when the redesign is ready.

**Comment by jamessspanggg** [comment] 2020-11-13 07:57
The issue is that the team members are sorted based on the `created_date`, instead of the `contributorId` as shown here:
https://github.com/thenewboston-developers/Website/blob/078f8d4cf949c544a9719d3fd88ebaf43c8d4174/src/utils/data.ts#L67-L73

Changing it should be fine. @manishram will you be working on it?

**Comment by manishram** [comment] 2020-11-13 08:15
Yeah sure @jamessspanggg go ahead. I am working on another issue right now. :)

**Closed** 2020-11-13 22:57 UTC
Labels: 500, bug
