### ISSUE TITLE
UNIT TESTS - components/DropdownInput

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1351] opened 2021-02-21 02:54 UTC
## What

Create unit tests using [Jest](https://jestjs.io/en/) and [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/).

Here are a couple examples of how unit tests should be created:

1. [Unit tests for our A component](https://github.com/thenewboston-developers/Website/blob/development/src/components/A/A.test.tsx)
2. [Unit tests for Icon component](https://github.com/thenewboston-developers/ui-js/blob/master/src/components/Icon/Icon.test.tsx)
3. [Unit tests for Button component](https://github.com/thenewboston-developers/ui-js/blob/master/src/components/Inputs/Button/Button.test.tsx)

## General Acceptance Criteria for writing Unit tests

1. Should create a `[nameOfComponent].test.tsx` within the same directory of the component.
2. Should have tests that tests every `prop` of the component.
3. If there are any conditional logic within the component, there should be unit tests that accounts for each conditional branches.
4. `npm run test` should be passing.

## Specific Acceptance Criteria

1. make sure you tests for each prop

**Comment by amarjeet987** [comment] 2021-03-05 04:53
I'll take this.

**Comment by denistsoi** [comment] 2021-03-10 03:24
think we can close this

**Closed** 2021-03-10 05:32 UTC
Labels: PR Reward - 2000

**Comment by amarjeet987** [comment] 2021-03-11 04:46
@denistsoi please do self assign the issue / get it assigned by commenting and check if the issue is already assigned to someone else before you start working on it. Much easier to keep track that way, and would save everyone's. Say for instance, this issue itself. I was working on this issue, I would've moved on to something else if I knew you were working on it too.
