### ISSUE TITLE
Website Not Opened In Following Mobile And Tablet Devices

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#1078] opened 2020-12-05 09:14 UTC
**Bug Description**
Mentioned iPhone mobiles and tablets website not shown it

iphone 6 s plus  - https://prnt.sc/vw8aq7
iphone 6s  -       https://prnt.sc/vw8bg3	
iphone 6 plus -    https://prnt.sc/vw8cp0
iphone 6 -         https://prnt.sc/vw8d9c
iphone 5s -        https://prnt.sc/vw8dok

Following iPad Devices Website Not shown it
ipad Air 2 - https://prnt.sc/vw8tf5
ipad Air - https://prnt.sc/vw8utr
ipad 4 - https://prnt.sc/vw8vo5
ipad mini 3 - https://prnt.sc/vw8xej
 ipad mini 2 - https://prnt.sc/vw8xvs

**Expected behavior**
Website support mentioned device

**Actual behavior**
The website, not support the mentioned device

**Comment by Hristijan95** [comment] 2020-12-05 11:27
Duplicate of #534

**Closed by Hristijan95** 2020-12-05 11:27 UTC
Labels: bug
