### ISSUE TITLE
Feedback submission failing

### ISSUE THREAD

**Issue by Creatinas** [thenewboston-developers/Website#2144] opened 2021-11-10 21:02 UTC
**Bug Description**
When trying to submit feedback form with valid information, it fails

**Steps to Reproduce**
1. Go to https://thenewboston.com/faq/all
3. Scroll down to feedback form
4. Enter all information
5. Submit

**Expected behavior**
Form is submitted, user is notified about successful submission.

**Actual behavior**
Form submission fails. User gets toast message - "Sorry, there was an error with your submission. Please try again later."
Post request returns {
  "detail": "Request was throttled. Expected available in 85116 seconds."
}

**OS and Browser**
 - OS: macOS Big Sur 11.6
 - Browser: Chrome

**Account Number**
679aff9a630beb883cc10368a2dedb7722e63b682143ae9fd2e051c13b710752

**Comment by jamessspanggg** [comment] 2021-11-12 13:41
@Creatinas hmm are you still facing this issue? I can't reproduce it on my side

**Comment by Creatinas** [comment] 2021-11-12 21:41
@jamessspanggg looks like its working right now, maybe temp issue.

**Comment by jamessspanggg** [comment] 2021-11-13 16:09
> Also form fields especially textarea should be with limited input. I just tried adding much more text into it and getting 502 response code.

yep actually i made the changes for those, thanks for the catch. Closing this for now

**Closed by jamessspanggg** 2021-11-13 16:09 UTC
Labels: bug, Not Ready
