### ISSUE TITLE
[FAQ] Hash Links does not snap correctly to the question title

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#659] opened 2020-11-09 17:31 UTC
**Bug Description**
When clicking the hashlink of a particular question, the does not snap correctly to the position of the question.

**Steps to Reproduce**
1. Go to FAQ page
2. Click on hash link of the question `Who created thenewboston`?
3. Observe that the question is covered

**Expected behavior**
The question is exactly in the view.

**Actual behavior**
The question is covered.

**Screenshots/Recordings**
![thenewbostonq abug](https://user-images.githubusercontent.com/32864116/98575571-51857f00-22f4-11eb-9738-87cf655982ca.gif)

**OS and Browser**
 - OS: Mac
 - Browser: Chrome and Safari

**Additional context**
May be due snapping not considering the height of the navbar.

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by jamessspanggg** [comment] 2020-11-09 17:36
Am happy to work on the issue if needed :)

**Comment by jamessspanggg** [comment] 2020-11-09 17:55
@lapstjup may I be assigned for this issue?

**Comment by thesanjeevsharma** [comment] 2020-11-09 18:22
@lapstjup @jamessspanggg This is a duplicate of #407. Closing this.

**Closed by thesanjeevsharma** 2020-11-09 18:22 UTC
Labels: 2000, bug
