### ISSUE TITLE
x-scroll issue

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1839] opened 2021-06-10 04:48 UTC
There is a x-scroll on the window when it should be responsive instead. Tested on the download page.

<img width="1120" alt="Screen Shot 2021-06-09 at 9 47 30 PM" src="https://user-images.githubusercontent.com/8547538/121466565-803c0480-c96c-11eb-98f9-b09d600bdc60.png">

**Comment by jamessspanggg** [comment] 2021-06-10 12:43
@buckyroberts cant seem to reproduce this, may I get the exact viewport width that it is occurring?

**Comment by angle943** [comment] 2021-06-10 22:21
you mean x-scroll, right?

**Comment by jamessspanggg** [comment] 2021-06-11 14:58
cannot replicate in both safari and chrome :( shall we close this if it can't be reproduced anymore?

**Comment by mtrierweiler** [comment] 2021-06-11 16:26
> cannot replicate in both safari and chrome :( shall we close this if it can't be reproduced anymore?

I just checked the downloads page and can confirm there is an x-scroll bar. I get it on all window sizes. I was using Chrome.

**Comment by mtrierweiler** [comment] 2021-06-11 17:38
It appears to be due to the class `.Download__main-background{width:100vw}`. This appears to have been done to get the background color to span the page (out of the bounds that the layout div puts on it). The Purpose appears to be to differentiate it from the release notes below it. By setting it to `width:100vw` while the y-scroll bar is present it will cause the x-scroll bar to show.

**Comment by jamessspanggg** [comment] 2021-06-12 00:42
> > cannot replicate in both safari and chrome :( shall we close this if it can't be reproduced anymore?
> 
> I just checked the downloads page and can confirm there is an x-scroll bar. I get it on all window sizes. I was using Chrome.

feel free to create a fix, I still can't seem to replicate it

**Comment by mtrierweiler** [comment] 2021-06-12 01:23
Ya I can get to it tomorrow after work unless someone wants to get on it sooner

**Comment by avinashupadhya99** [comment] 2021-06-12 09:58
Hi, I can confirm that I can reproduce this. I will work on this if it is alright

**Comment by roovy54** [comment] 2021-06-12 11:04
Hello thenewboston!
This is my first contribution.

## Removed the x-scroll bar [#1853](https://github.com/thenewboston-developers/Website/pull/1853)

**Comment by angle943** [comment] 2021-06-16 03:23
I am going to work on this. Note to self: https://github.com/thenewboston-developers/Website/pull/1852

**Closed** 2021-06-26 02:47 UTC
Labels: PR Reward - 1000, bug
