### ISSUE TITLE
details for each member in the team page not showing fully on smaller devices

### ISSUE THREAD

**Issue by benjithorpe** [thenewboston-developers/Website#607] opened 2020-11-08 04:46 UTC
**Bug Description**
On smaller devices/view-port, the details for each team member is not shown completely

**Steps to Reproduce**
1. Go to https://thenewboston.com/teams
2. Resize the browser if you are using a laptop/desktop

**Expected behavior**
The details need to be visible

**Actual behavior**
only the first few letters/words are visible on smaller devices

**Screenshots/Recordings**
![profile bug](https://user-images.githubusercontent.com/61359802/98457140-cf267f00-217c-11eb-98a2-60d7ef3e415d.png)

**OS and Browser**
 - OS: Linux
 - Browser Opera, Firefox, Chrome(mobile)

**Comment by thesanjeevsharma** [comment] 2020-11-08 07:01
@benjithorpe Duplicate of #547. Closing this.

**Closed by thesanjeevsharma** 2020-11-08 07:01 UTC
Labels: bug
