### ISSUE TITLE
[Internet Explorer] Website Not Loading

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#536] opened 2020-11-06 09:24 UTC
**Bug Description**
Website not open In internet Explorer

**Steps to Reproduce**
1. Go to 'IE' (internet Explorer)
2.Enter Following Url "https://thenewboston.com/" 

**Expected behavior**
Website supports Every Browser 

**Actual behavior**
Website not supports internet explorer

**Screenshots/Recordings**
https://prnt.sc/vejidh

Source URL: https://thenewboston.com/
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1920x880 |

**Comment by zinoadidi** [comment] 2020-11-06 10:22
I will fix this

**Comment by thesanjeevsharma** [comment] 2020-11-06 10:33
@webdeveloperswj @angle943 I think this issue is a duplicate of #211

**Comment by zinoadidi** [comment] 2020-11-06 11:42
#542 Pull request submitted

**Comment by thesanjeevsharma** [comment] 2020-11-08 08:58
Closing because this is a duplicate issue.

**Closed by thesanjeevsharma** 2020-11-08 08:58 UTC
Labels: bug
