### ISSUE TITLE
FAQ clicking title issue on homepage 

### ISSUE THREAD

**Issue by markmendozadev** [thenewboston-developers/Website#2047] opened 2021-09-12 14:18 UTC
**Bug Description**
On FAQ on the homepage when clicking the title the page scrolls into the question and it's making the question you clicked to go to the top. 

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/'
3. Scroll down to 'Bottom until you see the FAQ and click on one of the titles'
4. See an error

**Expected behavior**
When I click on the title the position of my screen should be the same. and when the title is clicked it will just open the card. not put the title on the top of my screen. 

**Actual behavior**
The FAQ on the homepage makes the position of title on the top when you clicked it. 

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/57791540/132990933-2123967a-ff37-4b12-b751-45d765ad3926.png)

**OS and Browser**
 - Browser Chrome

**Account Number**
6a25290a1c04252563d286790194bfd341e2656bcad17e9bbf75d7a626946067

**Comment by jamessspanggg** [comment] 2021-09-12 15:00
Duplicate of #1989

**Closed by jamessspanggg** 2021-09-12 15:00 UTC
Labels: bug, Not Ready
