### ISSUE TITLE
This page Images are not shown it

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#1079] opened 2020-12-05 09:19 UTC
**Bug Description**
Images are not shown it

**Steps to Reproduce**
1. Go to " https://thenewboston.com/teams"
2. see the profile images

**Expected behavior**
images are shown it

**Actual behavior**
images are not shown it

**Screenshots/Recordings**
https://prnt.sc/vw90ot

**OS and Browser**
 - OS:  Windows 10
 - Browser  Chrome

**Comment by Hristijan95** [comment] 2020-12-05 11:30
@webdeveloperswj , how did you reproduce this? The images are working on my end, maybe the slack server was down for a moment when you tried loading them and since we load images from direct URLs from slack, they failed to load.

**Comment by manishram** [comment] 2020-12-09 15:54
Plausibly it was with the slack server for that issue. But now images are loading from their Github profile and no more from slack. 
Fixed by: https://github.com/thenewboston-developers/Website/pull/1081

The issue can be closed I believe.

**Comment by webdeveloperswj** [comment] 2020-12-10 12:57
But still some images are not shown it
 https://thenewboston.com/teams
on this page following images not see it
screenshot:-
https://prnt.sc/vzrehi
https://prnt.sc/vzretf
https://prnt.sc/vzrf5g

**Comment by manishram** [comment] 2020-12-10 13:18
Yeah, I see some images are loading from slack. But I can not reproduce the bug. They seem to work well.
I using Windows 10 and Google Chrome.

**Screenshot**:
http://prnt.sc/vzrx25

**Comment by manishram** [comment] 2020-12-10 13:21
Yeah, I see some images are loading from slack. But I can not reproduce the bug. They seem to work well.
I am using Windows 10 and Google Chrome.

**Screenshot**:
http://prnt.sc/vzrx25

Can you check the network tab in google chrome and see the response for image requests?

**Comment by webdeveloperswj** [comment] 2020-12-14 13:57
Now At my End, All images are shown properly

**Comment by etfaghaoubeid** [comment] 2021-02-03 09:24
@webdeveloperswj  i will work on this bug

**Closed** 2021-02-28 22:45 UTC
Labels: bug
